=== behrouz-shafaati/Alba-cms-v0.2/lib/i18n/locales/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "lang": { "type": "string" },
    "language": { "type": "string" },
    "dir": { "type": "string" },
    "shared": {
      "type": "object",
      "properties": {
        "chooseYorLanguage": { "type": "string" },
        "mongodbUri": { "type": "string" },
        "failMongodbConnection": { "type": "string" },
        "next": { "type": "string" },
        "previous": { "type": "string" },
        "dbError": { "type": "string" },
        "fillForm": { "type": "string" },
        "login": { "type": "string" }
      },
      "required": [
        "chooseYorLanguage",
        "next",
        "previous",
        "mongodbUri",
        "failMongodbConnection",
        "fillForm",
        "dbError",
        "login"
      ]
    },
    "installer": {
      "type": "object",
      "properties": {
        "title": { "type": "string" },
        "chooseLanguage": { "type": "string" },
        "steps": {
          "type": "object",
          "properties": {
            "dashboard_lang": {
              "type": "object",
              "properties": {
                "title": { "type": "string" }
              },
              "required": ["title"]
            },
            "db": {
              "type": "object",
              "properties": {
                "title": { "type": "string" }
              },
              "required": ["title"]
            },
            "admin": {
              "type": "object",
              "properties": {
                "title": { "type": "string" }
              },
              "required": ["title"]
            },
            "suported_lang": {
              "type": "object",
              "properties": {
                "title": { "type": "string" }
              },
              "required": ["title"]
            },
            "finish": {
              "type": "object",
              "properties": {
                "title": { "type": "string" },
                "description": { "type": "string" }
              },
              "required": ["title", "description"]
            }
          },
          "required": [
            "dashboard_lang",
            "db",
            "admin",
            "suported_lang",
            "finish"
          ]
        }
      },
      "required": ["title", "chooseLanguage", "steps"]
    },
    "input": {
      "type": "object",
      "properties": {
        "combobox": {
          "type": "object",
          "properties": {
            "placeholder": { "type": "string" }
          },
          "required": ["placeholder"]
        }
      },
      "required": ["combobox"]
    },
    "user": {
      "type": "object",
      "properties": {
        "fName": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "required_error": { "type": "string" }
          },
          "required": ["title", "required_error"]
        },
        "lName": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "required_error": { "type": "string" }
          },
          "required": ["title", "required_error"]
        },
        "email": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "valid_error": { "type": "string" },
            "required_error": { "type": "string" }
          },
          "required": ["title", "required_error", "valid_error"]
        },
        "mobile": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "required_error": { "type": "string" }
          },
          "required": ["title", "required_error"]
        },
        "password": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "min_error": { "type": "string" },
            "required_error": { "type": "string" }
          },
          "required": ["title", "required_error", "min_error"]
        },
        "confirmPassword": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "dontEqual_error": { "type": "string" },
            "required_error": { "type": "string" }
          },
          "required": ["title", "required_error", "dontEqual_error"]
        },
        "createSuccessful": { "type": "string" }
      },
      "required": [
        "fName",
        "confirmPassword",
        "password",
        "mobile",
        "email",
        "lName",
        "createSuccessful"
      ]
    },
    "languages": {
      "type": "object",
      "properties": {
        "locales": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "required_error": { "type": "string" },
            "placeholder": { "type": "string" }
          },
          "required": ["title", "required_error", "placeholder"]
        },
        "siteDefault": {
          "type": "object",
          "properties": {
            "title": { "type": "string" },
            "required_error": { "type": "string" },
            "placeholder": { "type": "string" }
          },
          "required": ["title", "required_error", "placeholder"]
        },
        "success": { "type": "string" }
      },
      "required": ["locales", "siteDefault", "success"]
    }
  },
  "required": ["installer", "input", "user"]
}

=== behrouz-shafaati/Alba-cms-v0.2/lib/i18n/install/locales/en.json
{
  "$schema": "./schema.json",
  "lang": "en",
  "language": "English",
  "dir": "ltr",
  "shared": {
    "chooseYorLanguage": "Choose your language",
    "next": "Next",
    "previous": "Previous",
    "mongodbUri": "Mongodb URI",
    "failMongodbConnection": "Connection to database failed.",
    "fillForm": "Please fill in the required fields.",
    "dbError": "Database error",
    "login": "Login"
  },
  "installer": {
    "title": "Installation",
    "chooseLanguage": "Choose language",
    "steps": {
      "dashboard_lang": {
        "title": "Your language"
      },
      "db": {
        "title": "Database"
      },
      "admin": {
        "title": "Create admin"
      },
      "suported_lang": {
        "title": "Site Languages"
      },
      "finish": {
        "title": "Finish",
        "description": "Configuration completed successfully ðŸ¥³"
      }
    }
  },
  "input": {
    "combobox": {
      "placeholder": "Choose"
    }
  },
  "user": {
    "fName": {
      "title": "First name",
      "required_error": "Please enter your name."
    },
    "lName": {
      "title": "Last name",
      "required_error": "Please enter your last name."
    },
    "email": {
      "title": "Email",
      "required_error": "Please enter your email.",
      "valid_error": "Please enter a valid email."
    },
    "mobile": {
      "title": "Mobile",
      "required_error": "Please enter your mobile."
    },
    "password": {
      "title": "Password",
      "required_error": "Please enter your password.",
      "min_error": "The password must be at least 6 characters long."
    },
    "confirmPassword": {
      "title": "Confirm password",
      "required_error": "Please enter password confirmation.",
      "dontEqual_error": "Password confirmation is not the same as a password."
    },
    "createSuccessful": "User created successfully."
  },
  "languages": {
    "locales": {
      "title": "Site languages",
      "placeholder": "Choose your site languages...",
      "required_error": "Please select your site languages."
    },
    "siteDefault": {
      "title": "Default language",
      "placeholder": "Select default language...",
      "required_error": "Please select your default site language."
    },
    "success": "Languages â€‹â€‹were successfully set."
  }
}

=== behrouz-shafaati/Alba-cms-v0.2/lib/i18n/locales/fa.json
{
  "$schema": "./schema.json",
  "lang": "fa",
  "language": "ูุงุฑุณ",
  "dir": "rtl",
  "shared": {
    "chooseYorLanguage": "ุฒุจุงูุชุงู ุฑุง ุงูุชุฎุงุจ ฺฉูุฏ",
    "failMongodbConnection": "ุงุชุตุงู ุจู ูพุงฺฏุงู ุฏุงุฏู ูุงูููู ุจูุฏ.",
    "next": "ุจุนุฏ",
    "previous": "ูุจู",
    "mongodbUri": "Mongodb URL",
    "fillForm": "ูุทูุง ููุฏูุง ูุงุฒู ุฑุง ูพุฑ ฺฉูุฏ.",
    "dbError": "ุฎุทุง ูพุงฺฏุงู ุฏุงุฏู.",
    "login": "ูุงุฑุฏ ุดูุฏ"
  },
  "installer": {
    "title": "ูุตุจ ุงููู",
    "chooseLanguage": " ุฒุจุงู",
    "steps": {
      "admin": { "title": "ุณุงุฎุช ูุฏุฑ" },
      "finish": {
        "title": "ูพุงุงู",
        "description": "ูพฺฉุฑุจูุฏ ุจุง ููููุช ุงูุฌุงู ุดุฏ ๐ฅณ"
      },
      "dashboard_lang": { "title": "ุฒุจุงู ุดูุง" },
      "db": { "title": "ูพุงฺฏุงู ุฏุงุฏู" },
      "suported_lang": { "title": "ุฒุจุงูโูุง ุณุงุช" }
    }
  },
  "input": { "combobox": { "placeholder": "ุงูุชุฎุงุจ ฺฉูุฏ" } },
  "user": {
    "fName": { "title": "ูุงู", "required_error": "ูุทูุง ูุงู ุฑุง ูุงุฑุฏ ฺฉูุฏ." },
    "lName": {
      "title": "ูุงู ุฎุงููุงุฏฺฏ",
      "required_error": "ูุทูุง ูุงู ุฎุงููุงุฏฺฏ ุฑุง ูุงุฑุฏ ฺฉูุฏ."
    },
    "email": {
      "title": "ุงูู",
      "required_error": "ูุทูุง ุงูู ุฑุง ูุงุฑุฏ ฺฉูุฏ.",
      "valid_error": "ูุทูุง ุงูู ูุนุชุจุฑ ูุงุฑุฏ ฺฉูุฏ."
    },
    "mobile": {
      "title": "ููุจุงู",
      "required_error": "ูุทูุง ููุจุงู ุฑุง ูุงุฑุฏ ฺฉูุฏ."
    },
    "password": {
      "title": "ุฑูุฒ ูุฑูุฏ",
      "required_error": "ูุทูุงู ุฑูุฒ ูุฑูุฏ ุฑุง ูุงุฑุฏ ฺฉูุฏ.",
      "min_error": "ุฑูุฒ ูุฑูุฏ ุจุงุฏ ุญุฏุงูู ถ ฺฉุงุฑุงฺฉุชุฑ ุจุงุดุฏ."
    },
    "confirmPassword": {
      "title": "ุชฺฏุฑุงุฑ ุฑูุฒ ูุฑูุฏ",
      "required_error": "ูุทูุง ุชุงุฏ ุฑูุฒ ูุฑูุฏ ุฑุง ูุงุฑุฏ ฺฉูุฏ.",
      "dontEqual_error": "ุชุงุฏ ุฑูุฒ ุนุจูุฑ ุจุง ุฑูุฒ ุนุจูุฑ ุจุฑุงุจุฑ ูุณุช."
    },
    "createSuccessful": "ฺฉุงุฑุจุฑ ุจุง ููููุช ุงุฌุงุฏ ุดุฏ."
  },
  "languages": {
    "locales": {
      "title": "ุฒุจุงูโูุง ุณุงุช",
      "placeholder": "ุฒุจุงูโูุง ุณุงุช ุฑุง ุงูุชุฎุงุจ ฺฉูุฏ...",
      "required_error": "ูุทูุง ุฒุจุงูโูุง ุณุงุช ุฎูุฏ ุฑุง ุงูุชุฎุงุจ ฺฉูุฏ."
    },
    "siteDefault": {
      "title": "ุฒุจุงู ูพุด ูุฑุถ",
      "placeholder": "ุฒุจุงู ูพุดโูุฑุถ ุณุงุช ุฑุง ุงูุชุฎุงุจ ฺฉูุฏ...",
      "required_error": "ูุทูุง ุฒุจุงู ูพุดโูุฑุถ ุณุงุช ุฎูุฏ ุฑุง ุงูุชุฎุงุจ ฺฉูุฏ."
    },
    "success": "ุฒุจุงูโูุง ุจุง ููููุช ุชูุธู ุดุฏูุฏ."
  }
}
